### ISSUE TITLE
Cannot build - digital envelope routines::unsupported

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#194]
```

nginx@xrg13:/opt/dcat-ap-forms$ HOME=/home/nginx npm run build -- --env configFileLocation=./nkod.config.js

> dcat-ap-forms-vue@2.0.0-alpha.2 build
> cross-env NODE_ENV=production webpack --config build/webpack.production.js "--env" "configFileLocation=./nkod.config.js"

Loading configuration from:  ./nkod.config.js
(node:3073) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/opt/dcat-ap-forms/node_modules/webpack/lib/util/createHash.js:138:18)
    at BulkUpdateDecorator.update (/opt/dcat-ap-forms/node_modules/webpack/lib/util/createHash.js:44:50)
    at RawSource.updateHash (/opt/dcat-ap-forms/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/opt/dcat-ap-forms/node_modules/webpack/lib/NormalModule.js:737:17)
    at handleParseResult (/opt/dcat-ap-forms/node_modules/webpack/lib/NormalModule.js:801:10)
    at /opt/dcat-ap-forms/node_modules/webpack/lib/NormalModule.js:854:4
    at processResult (/opt/dcat-ap-forms/node_modules/webpack/lib/NormalModule.js:625:11)
    at /opt/dcat-ap-forms/node_modules/webpack/lib/NormalModule.js:676:5
    at /opt/dcat-ap-forms/node_modules/loader-runner/lib/LoaderRunner.js:404:3
    at iterateNormalLoaders (/opt/dcat-ap-forms/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at iterateNormalLoaders (/opt/dcat-ap-forms/node_modules/loader-runner/lib/LoaderRunner.js:240:10)
    at /opt/dcat-ap-forms/node_modules/loader-runner/lib/LoaderRunner.js:255:3
    at context.callback (/opt/dcat-ap-forms/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /opt/dcat-ap-forms/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.0.0

```

**Comment by jakubklimek** [comment]
Actually, this is the same as https://github.com/linkedpipes/dcat-ap-viewer/issues/270

**Comment by skodapetr** [comment]
Duplicate to #193
